#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py makemigrations
python manage.py migrate
# python manage.py compress # for production mode (django compressor)
python manage.py collectstatic --noinput
uvicorn config.asgi:application --host 0.0.0.0 --reload
